In [2]:
import cv2
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers , models
import numpy as np
import pandas as pd

In [9]:
face_detector = cv2.CascadeClassifier (cv2.data.haarcascades + "haarcascade_frontalface_default.xml")
Gender_model = models.load_model("Gender.h5")
Age_model = models.load_model("Age.h5")


vid = cv2.VideoCapture(0)
while (True):
    ret , frame = vid.read()
    Gray_color = cv2.cvtColor(frame , cv2.COLOR_BGR2GRAY)
    face = face_detector.detectMultiScale(Gray_color)
    for (x , y , w , h) in face:
        cv2.rectangle(frame , (x , y ) , (x + w , y +h) , (255 , 0 , 0) , 3)
        Face = frame[y:y+h , x:x+w]
        face_resized = cv2.resize(Face, (64, 64),interpolation =cv2.INTER_AREA)
        face_flatten = face_resized / 255.0
        face_flatten = face_flatten.flatten()
        face_flatten = np.expand_dims(face_flatten, axis=0)
        
        pred = Gender_model.predict(face_flatten) 
        print (pred)
        if pred[0][0] > 0.5:
            label = 'Man'
        else:
            label = 'Woman'
        print (label)
        cv2.putText(frame, label, (x, y - 10), cv2.FONT_HERSHEY_SIMPLEX, 0.9, (0 , 255 , 0) , 2)
        
        output = Age_model.predict(face_flatten)
        print(output)
        max_output = np.argmax(output)
        print(max_output)
        category_name = ['0-10', '11-20', '21-30', '31-40', '41-50', '51-60', '61-70', '71-80', '81-90', '91-More']
        print(category_name[max_output])    
        
        cv2.putText(frame, category_name[max_output], (x, y - 30), cv2.FONT_HERSHEY_SIMPLEX, 0.9, (0 , 255 , 0) , 2)

    cv2.imshow("Mehdi_Ganji_Project" , frame)
    if cv2.waitKey(1) & 0xFF == ord("q"):
        break
vid.release()
cv2.destroyAllWindows()

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step
[[0.00480296 0.993956  ]]
Woman
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 90ms/step
[[0.04970087 0.01316233 0.04621948 0.08309174 0.10971492 0.3159104
  0.21155022 0.11836836 0.04691019 0.00537139]]
5
51-60
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step
[[0.00740224 0.99057   ]]
Woman
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step
[[0.0520736  0.01115717 0.04017778 0.07453737 0.10121454 0.3214929
  0.22062069 0.12293994 0.04982009 0.00596582]]
5
51-60
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step
[[0.00168134 0.9978592 ]]
Woman
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step
[[0.05376769 0.01237964 0.04149837 0.07484592 0.10104891 0.30933174
  0.22111897 0.12584855 0.05316623 0.006994  ]]
5
51-60
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step
[[0.00549351 0.99286157]]
Woman
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step
[[0.052572   0.00935224 0.03355211 0.06320428 0.09243096 0.30824375
  0.23703533 0.13960555 0.05724395 0.00675983]]
5
51-60
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step
[[0.0013961 0.9982001]]
Woman
1/1 ━━

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step
[[0.04506171 0.01618966 0.05636509 0.09757656 0.12377615 0.30950177
  0.19636227 0.1097791  0.04118855 0.00419912]]
5
51-60
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step
[[0.10856827 0.8867144 ]]
Woman
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step
[[0.04248998 0.02291374 0.07089199 0.11518438 0.138529   0.29057518
  0.18140988 0.0981608  0.03605648 0.00378855]]
5
51-60
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step
[[2.8775167e-04 9.9965960e-01]]
Woman
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step
[[0.05001904 0.01591342 0.0515217  0.08869842 0.11426432 0.30208266
  0.20619997 0.11746366 0.04793721 0.00589963]]
5
51-60
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step
[[3.775685e-04 9.995279e-01]]
Woman
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step
[[0.05161051 0.02491814 0.06491113 0.10037459 0.1222231  0.266035
  0.19393796 0.1159975  0.05197911 0.00801297]]
5
51-60
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step
[[0.01296661 0.98395324]]
Woman
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step
[[0.04910188 0.01497939 0.

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step
[[0.04747514 0.02680293 0.12727642 0.16676186 0.16396983 0.2641979
  0.12171581 0.06629045 0.01506639 0.00044334]]
5
51-60
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step
[[0.03543775 0.95908165]]
Woman
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step
[[0.03774635 0.02684702 0.0839585  0.13041228 0.15112503 0.27535772
  0.16434409 0.09368929 0.03342271 0.00309703]]
5
51-60
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step
[[1.3923892e-04 9.9987727e-01]]
Woman
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step
[[0.09069357 0.03902376 0.13168384 0.14624414 0.13615069 0.2300217
  0.13433447 0.07143747 0.01945714 0.00095321]]
5
51-60
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step
[[0.07055972 0.9233501 ]]
Woman
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step
[[0.03946193 0.02278087 0.07483333 0.12068762 0.14379147 0.28863555
  0.17357461 0.09797314 0.03502096 0.00324057]]
5
51-60
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step
[[3.3588448e-04 9.9967951e-01]]
Woman
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step
[[0.12850592 0.06625033 

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step
[[0.12444482 0.05237445 0.14657749 0.13616031 0.11934488 0.18398684
  0.12655337 0.08181748 0.02703824 0.00170208]]
5
51-60
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step
[[0.38919917 0.5740698 ]]
Woman
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step
[[0.05829673 0.05083405 0.11049044 0.13402657 0.13926312 0.20970249
  0.15265927 0.09693623 0.0419741  0.00581695]]
5
51-60
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step
[[0.01090824 0.98396087]]
Woman
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step
[[0.04521724 0.01503486 0.04088426 0.06527009 0.10364551 0.22804421
  0.24047382 0.17959437 0.07388728 0.00794839]]
6
61-70
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step
[[0.7184106 0.2740046]]
Man
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step
[[0.2949716  0.23834334 0.18896215 0.08109907 0.04843922 0.04226262
  0.05211721 0.03323029 0.01678437 0.00379022]]
0
0-10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step
[[0.01300842 0.98232096]]
Woman
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step
[[0.03699819 0.02009537 0.06851418 0.11